spring:
  application:
    name: service-reservation

server:
  port: 8081

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true

#eureka.client.enabled=false
#spring.cloud.config.uri=http://localhost:8888
#spring.cloud.config.discovery.enabled=true
#spring.cloud.config.discovery.serviceId=config