spring:
  application:
    name: service-eureka

server:
  port: 8761

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  instance:
    hostname: discovery
#eureka.client.enabled=false
#spring.cloud.config.uri=http://localhost:8888
#spring.cloud.config.discovery.enabled=true
#spring.cloud.config.discovery.serviceId=config